### PR TITLE
Updated Text for BNR-DE-500 - for translation

### PR DESCRIPTION
**Pull request by kerstin-oppermann-tsi**
Text was changed because the 1st october is in the past. Has to be done in the other languages too.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
- This relates to issue https://github.com/corona-warn-app/dcc-rule-translation/issues/15

**Comment by MikeMcC399** [comment]
@kerstin-oppermann-tsi 

The date in English would be "1st October" or just "1 October". 
There is no 1th because the word is "first" abbreviated to 1st. 
It's 1st, 2nd, 3rd, 4th, 5th etc. as abbreviations.
"of" is spoken, but not written.

**Comment by kerstin-oppermann-tsi** [comment]
> @kerstin-oppermann-tsi
> 
> The date in English would be "1st October" or just "1 October". There is no 1th because the word is "first" abbreviated to 1st. It's 1st, 2nd, 3rd, 4th, 5th etc. as abbreviations. "of" is spoken, but not written.

Yes that's correct. But it is only the comment and we have to follow the regular way of translation from german to the other languages.

**Comment by mlenkeit** [comment]
@MikeMcC399 thanks for the remark, I'm sure the translation team will take this into consideration!

**Review by mlenkeit — APPROVED** [review]

**Comment by MikeMcC399** [comment]
@mlenkeit 

I noticed that the rule name in the text has been changed from `(Regel DE-BNR-0500)` to `(Regel BNR-DE-0500)` which makes it agree with `<string name="BNR-DE-0500">`.

Should a similar change also be applied to the text in the other active rule `<string name="BNR-DE-0400">` / `(Regel DE-BNR-0400)`?

**Comment by kerstin-oppermann-tsi** [comment]
@MikeMcC399 thx, we will change this asap in BNR-DE-0400 too. We will check the other active and inactive rules for that mismatch.

**Pull request merged**
